# syntax=docker/dockerfile:experimental
#############
### build ###
#############
FROM python:3.9-alpine as base

FROM base as builder
RUN apk add --no-cache gcc musl-dev

# install galileo dependencies
COPY requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

############
### prod ###
############
FROM base
COPY --from=builder  /usr/local /usr/local

RUN mkdir /app
WORKDIR /app

COPY lbopt lbopt

ENTRYPOINT ["python", "-u", "-m", "lbopt.cli.daemon"]
